server { 
        listen 80 default_server;
        listen [::]:80 default_server;

        index index.html;

        location / { 
                root /usr/share/nginx/html;
                try_files $uri /index.html; 
                }

                
        }
server {
      listen 443 ssl;
      listen [::]:443 ssl;
      server_name erickaericksonportfolio.com www.erickaericksonportfolio.com;

      ssl_certificate
  /etc/letsencrypt/live/erickaericksonportfolio.com/fullchain.pem;
      ssl_certificate_key
  /etc/letsencrypt/live/erickaericksonportfolio.com/privkey.pem;

      index index.html;

      location / {
          root /usr/share/nginx/html;
          try_files $uri /index.html;
      }
  }